### ISSUE TITLE
font-awesome is removed

### ISSUE THREAD

**Issue by ikedas** [ikedas/sympa-rpm#16]
Version: 6.2.23b.3
Platform: CentOS 6.9

If fontawesome-fonts(-web) have already been installed, then sympa package is updated to 6.2.23b.3, files included in fontawesome are removed.

``` bash
# yum install fontawesome-fonts-web
...
# yum update sympa
...
$ rpm -qV fontawesome-fonts fontawesome-fonts-web
missing     /usr/share/fonts/fontawesome/FontAwesome.otf
missing     /usr/share/fonts/fontawesome/fontawesome-webfont.ttf
missing     /usr/share/font-awesome-web/css/font-awesome.css
missing     /usr/share/font-awesome-web/css/font-awesome.min.css
missing     /usr/share/fonts/fontawesome/fontawesome-webfont.eot
missing     /usr/share/fonts/fontawesome/fontawesome-webfont.svg
missing     /usr/share/fonts/fontawesome/fontawesome-webfont.woff
missing     /usr/share/fonts/fontawesome/fontawesome-webfont.woff2
$
```

**Comment by xavierba** [comment]
This should fix the issue, but it's not tested yet:
https://github.com/xavierba/sympa-rpm/commit/b975c50c5c038780e42fbad31311d3f76156929d

**Comment by ikedas** [comment]
I thought out another way:
https://github.com/ikedas/sympa-rpm/commit/065b343996ef20354c1c82b9eaf36e416548b67f

(checked only with httpd and nginx)

**Comment by ikedas** [comment]
@xavierba, I confirmed it works with lighttpd, too.
